# Generated by Django 4.1.7 on 2023-02-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sorovnoma_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorovnoma',
            name='number_of_votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
