# Generated by Django 4.1.7 on 2023-02-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorovnoma',
            name='number_of_votes',
        ),
    ]
