# Generated by Django 4.1.7 on 2023-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sorovnoma_number_of_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sorovnoma',
            name='variants',
        ),
        migrations.AddField(
            model_name='sorovnoma',
            name='variants',
            field=models.ManyToManyField(blank=True, to='main.variant'),
        ),
    ]
