# Generated by Django 4.1.7 on 2023-03-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_variant_remove_sorovnoma_variants_sorovnoma_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorovnoma',
            name='users',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
