# Generated by Django 4.1.7 on 2023-03-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_sorovnoma_users_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredchannel',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='requiredchannel',
            name='username',
            field=models.CharField(default='diyorbeksblog', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='main.variant'),
        ),
    ]
